services:
  frontend-wishly:
    container_name: frontend-wishly
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3101:3101'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3101
      - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL}
    restart: unless-stopped
